### ISSUE TITLE
WorldGuard region data failing to load

### ISSUE THREAD

**Issue by RoloRotMG** [RotMC/Ephemera#1]
WorldGuard fails to load region data with newly made swm worlds

Have WorldGuard installed. Create a slime world in game and then go to it. Anytime you click an interactable block such as a barrel this message comes up
![image](https://user-images.githubusercontent.com/53577866/189628637-918721ca-e54a-4d50-b741-adda033d6d90.png)
I consulted the EngineHub discord (support for WorldGuard and they said "Sounds like that plugin has broken the Bukkit world lifecycle" in response to me using SWM, not sure who needs to do what here

After the world is created. If I type /worldguard reload it fixes for that world

**Comment by wordandahalf** [comment]
Caused by WorldGuard fork, no longer needed.
